services:
  habr-bot:
    image: habr-article-bot:latest
    container_name: habr-bot
    environment:
      botToken: "your:telegram-token"
      notifyStartStop: "False"
      enableWhitelist: "True"
      whitelist: "[chatid]"
      habrApiUrl: "https://habr.example.com/api"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
